### ISSUE TITLE
New dynamic spacing scale values treated as custom classes

### ISSUE THREAD

**Issue by sweetroll** [ttskch/prettier-plugin-tailwindcss-anywhere#3]
Thanks for your plugin!

Any spacing values that are not strictly specified in the theme are treated as custom classes and therefore reordered to the beginning of the string eg. 30 is not a default spacing value so if used it would look like this: lg:mb-30 bg-white font-bold md:mt-6 lg:mt-12.

Its currently working in the css though:

```
// CSS
@apply grid-cols-2 font-bold md:my-4 md:grid-cols-73 lg:my-4 lg:grid-cols-111 xl:-my-30;

// Twig file
<div class="md:grid-cols-73 lg:grid-cols-111 xl:-my-30 grid-cols-2 font-bold md:my-4 lg:my-4">
```

Using:
```
"tailwindcss": "^4.0.0-beta.8",
"prettier": "3.4.2",
"prettier-plugin-tailwindcss": "0.6.9",
"@ttskch/prettier-plugin-tailwindcss-anywhere": "0.0.7",
```

**Comment by ttskch** [comment]
@sweetroll 

I prepared the following project and ran prettier, and confirmed that it was formatted as `<div class="md:grid-cols-73 lg:grid-cols-111 xl:-my-30 grid-cols-2 font-bold md:my-4 lg:my-4">`.

```json5
// package.json
{
  "dependencies": {
    "prettier": "^3.4.2",
    "prettier-plugin-tailwindcss": "^0.6.9"
  }
}
```

```json5
// .prettierrc
{
  "plugins": ["prettier-plugin-tailwindcss"],
}
```

```html
<div class="grid-cols-2 font-bold md:my-4 md:grid-cols-73 lg:my-4 lg:grid-cols-111 xl:-my-30"></div>
```

```html
<!-- after `pnpm prettier --write index.html` -->
<div class="md:grid-cols-73 lg:grid-cols-111 xl:-my-30 grid-cols-2 font-bold md:my-4 lg:my-4"></div>
```

In other words, this behavior is a specification (or a bug) of `prettier-plugin-tailwindcss` itself.

Once `prettier-plugin-tailwindcss` is fixed, it will work as expected when used in conjunction with `prettier-plugin-tailwindcss-anywehere`.

Thanks.

**Comment by sweetroll** [comment]
Hi @ttskch it looks like running prettier via the CLI as in the example above is formatting the classes correctly now but not in my editor. Wuuld you be able to revisit this issue please?

Cheers
