### ISSUE TITLE
[HELP] Following the Usage section doesn't work for me

### ISSUE THREAD

**Issue by florianbouvot** [ttskch/prettier-plugin-tailwindcss-anywhere#4]
Hi,
I work on Twig project with tailwindcss v4 beta and I try to use prettier-plugin-tailwindcss-anywhere and `prettier-plugin-tailwindcss` but it doesn't works.

**What I do**

- Install `Prettier - Code formatter` in VSCode
- Install dependencies:

```
    // package.json
    "@ttskch/prettier-plugin-tailwindcss-anywhere": "^0.0.7",
    "prettier": "^3.4.2",
    "prettier-plugin-tailwindcss": "^0.6.9",
```

- Create Prettier config files with:

```
    // .prettierrc
    {
      "plugins": [
        "prettier-plugin-tailwindcss",
        "@ttskch/prettier-plugin-tailwindcss-anywhere"
      ],
      "overrides": [
        {
          "files": "*.html.twig",
          "options": {
            "parser": "anywhere"
          }
        }
      ],
      "trailingComma": "es5",
      "tabWidth": 2,
      "semi": false,
      "singleQuote": true,
      "useTabs": false
    }
```

Then I open Twig templates, add some Tailwind Classes and save, nothing
I try using `Shift + Option + F` and option "There is no formatter for 'plaintext' files installed.", I try to install different Twig Formatter Plugin but nothing works.

Can you help me and tell me more about yours settings, plugins, ...?

Thank you 😊

**Comment by ttskch** [comment]
@florianbouvot I don't use VS Code so I don't know the details about [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). Sorry.

But, I have confirmed that this plugin works properly with TailwindCSS v4 Beta by following the steps below.

```shell
$ pnpm init

$ pnpm add tailwindcss@next prettier prettier-plugin-tailwindcss @ttskch/prettier-plugin-tailwindcss-anywhere

$ cat package.json
{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@ttskch/prettier-plugin-tailwindcss-anywhere": "^0.0.7",
    "prettier": "^3.4.2",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "tailwindcss": "4.0.0-beta.8"
  }
}

$ echo '<p class="px-1 mx-1"></p>' > index.html.twig # <-- See here

$ echo '{
  "plugins": [
    "prettier-plugin-tailwindcss",
    "@ttskch/prettier-plugin-tailwindcss-anywhere"
  ],
  "overrides": [
    {
      "files": "*.html.twig",
      "options": {
        "parser": "anywhere"
      }
    }
  ],
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "useTabs": false
}' > .prettierrc

$ pnpm prettier --write index.html.twig

$ cat index.html.twig
<p class="mx-1 px-1"></p> # <-- See here
```

I recommend that you create a minimal configuration that will work with this plugin, and then add dependencies and configurations one by one to isolate the source of the problem.

Thanks.
